Re-added `@inheritDoc` that was dropped during `#[Override]` additions
Fixes:

```

Error: Method \DoctrineBatchUtilsTest\MockEntityManager::newHydrator() does not have parameter type hint nor @param annotation for its parameter $hydrationMode.
```